# Generated by Django 5.0.1 on 2024-09-15 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="mobile",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must start with '+' and contain up to 15 digits.",
                        regex="^\\+\\d{1,15}$",
                    )
                ],
            ),
        ),
    ]
